name: Basic Workflow Dispatch Example
on:
   workflow_dispatch:
    inputs:
      name:
        description: 'Test workflow_dispatch'
        required: true
        default: 'dispatch'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'
   
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
