name: Basic Workflow Dispatch Example
on:
  push:
    branches:
      - master
    paths:
      - 'version.txt'
  workflow_dispatch:
    inputs:
      version:
        description: 'The version to announce'
        type: string
        required: true
      description:
        description: 'A short description of the version to announce'
        type: string
        required: true
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
